version: "2"

services:

  nginx:
    image: nginx:latest
    ports:
    - "8080:80"
    volumes:
    - ./web:/var/www/html
    - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web

  php:
    image: php:7.1-fpm
    # image: php:5.6-fpm
    volumes:
      - ./web:/var/www/html
    networks:
      - web

  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: basic
      MYSQL_USER: basic
      MYSQL_PASSWORD: basic
    networks:
      - web

networks:
  web:
    driver: bridge